### ISSUE TITLE
query_rgb_cmsr

### ISSUE THREAD

**Issue by oyryrookie** [HeZongyao/LMF#2]
![1](https://github.com/HeZongyao/LMF/assets/166804840/ecb301ea-06c5-4733-bba4-d39de7f89e59)
首先我生成了使用init-div2k-x2.yaml生成了Generate Scale2Mod Table，demo.py中设置了parser.add_argument('--cmsr', default=True)，--scale 2, 添加了--cmsr_path  configs/cmsr/result/edsr-b_lm-liif_2e-5.yaml
请问我用demo.py进行单张图片的推理时，什么时候才会走query_rgb_cmsr呢？这个Only use CMSR for out-of-training scales是什么意思？

**Comment by oyryrookie** [comment]
> ![1](https://private-user-images.githubusercontent.com/166804840/335416398-ecb301ea-06c5-4733-bba4-d39de7f89e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzc0MjYsIm5iZiI6MTcxNzEzNzEyNiwicGF0aCI6Ii8xNjY4MDQ4NDAvMzM1NDE2Mzk4LWVjYjMwMWVhLTA2YzUtNDczMy1iYmE0LWQzOWRlN2Y4OWU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTA3ZGQ1YTBkMzc0N2I5M2Y2NGQzZWJmZTc4NmZjZmU4N2I1ODM5MjNhMmY2ZjUyNTY4ZDA3NDUxOGE2MjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6wG09v-Z_-2ubIYRun6nE-f458uHSOJIjC4RaoioyA) 首先我生成了使用init-div2k-x2.yaml生成了Generate Scale2Mod Table，demo.py中设置了parser.add_argument('--cmsr', default=True)，--scale 2, 添加了--cmsr_path configs/cmsr/result/edsr-b_lm-liif_2e-5.yaml 请问我用demo.py进行单张图片的推理时，什么时候才会走query_rgb_cmsr呢？这个Only use CMSR for out-of-training scales是什么意思？

我理解了Only use CMSR for out-of-training scales，是指大的放大倍数，比如6，8，12，18等等，但我设置--scale 8时，也不会使用query_rgb_cmsr，那什么时候才会使用这个query_rgb_cmsr呢？

**Comment by oyryrookie** [comment]
我理解了Only use CMSR for out-of-training scales，是指大的放大倍数，比如6，8，12，18等等，但当我设置--scale 8时，也不会使用query_rgb_cmsr，那什么时候才会使用这个query_rgb_cmsr呢？

**Comment by HeZongyao** [comment]
> 我理解了Only use CMSR for out-of-training scales，是指大的放大倍数，比如6，8，12，18等等，但当我设置--scale 8时，也不会使用query_rgb_cmsr，那什么时候才会使用这个query_rgb_cmsr呢？

out-of-training scales对应的是大于训练最大倍数（x4），正常的话8倍超分会用到query_rgb_cmsr，你可以看一下你的demo.py代码里的32行到46行有没有读取到cmsr_spec：    if args.cmsr:
        try:
            # Test with CMSR
            with open(args.cmsr_path, 'r') as f:
                s2m_tables = yaml.load(f, Loader=yaml.FullLoader)
            cmsr_spec = {
                "mse_threshold": float(args.cmsr_mse),
                "path": args.cmsr_path,
                "s2m_tables": s2m_tables,
                "log": False,
            }
        except FileNotFoundError:
            cmsr_spec = None
    else:
        cmsr_spec = None

**Comment by oyryrookie** [comment]
![image](https://github.com/HeZongyao/LMF/assets/166804840/c41c7ff6-4bd7-4ca2-9882-15a84d7e41c9)

读取到了，但是后面也不会用到这个query_rgb_cmsr
设置--scale 8也没用

![image](https://github.com/HeZongyao/LMF/assets/166804840/64d9488c-3d95-4906-92b9-1b8a7a9e3833)

**Comment by HeZongyao** [comment]
> ![image](https://private-user-images.githubusercontent.com/166804840/335544066-c41c7ff6-4bd7-4ca2-9882-15a84d7e41c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTE5MTYsIm5iZiI6MTcxNzE1MTYxNiwicGF0aCI6Ii8xNjY4MDQ4NDAvMzM1NTQ0MDY2LWM0MWM3ZmY2LTRiZDctNGNhMi05ODgyLTE1YTg0ZDdlNDFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDMzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2UxMTg2Y2MxZTk1NDJhYjhjYmRkZGMzOWUwYjc4M2RhOGQwNzk5NWY2YWVhMjMxNzg1M2M1MmEyNmE5ODJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4oI2lyatIkT3m-GGKgkg8h_R9XR_kN2tYG9R6WPn7do)
> 
> 读取到了，但是后面也不会用到这个query_rgb_cmsr 设置--scale 8也没用
> 
> ![image](https://private-user-images.githubusercontent.com/166804840/335544570-64d9488c-3d95-4906-92b9-1b8a7a9e3833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTE5MTYsIm5iZiI6MTcxNzE1MTYxNiwicGF0aCI6Ii8xNjY4MDQ4NDAvMzM1NTQ0NTcwLTY0ZDk0ODhjLTNkOTUtNDkwNi05MmI5LTFiOGE3YTllMzgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDMzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTk3MGQ5M2E3MWMwZmJkZjVmZjY4NDQ3ZTA5N2E5YmIzOTJmMDllMzI1OTg5NGI5OTk3MWY3YmZiNTA4OTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ITzJkjnJIgagsHX0c2R6zAZo7rN3yliTZ8pxkyAZ8QI)

demo.py少写了model.eval()，我改一下
