### ISSUE TITLE
LM-ciaoSR结果poor

### ISSUE THREAD

**Issue by jimoxiaonvsheng777** [HeZongyao/LMF#7]
其他模型训练的结果正确，但是LM-ciaosr的PSNR平均大概16db，为什么呢？还有一个问题测试LM-ciaosr时，一直out of memory,但是batch size=1，想问一下GPU的内存多大才可以测试，我的大概24G，但是还是out.

**Comment by jimoxiaonvsheng777** [comment]
找到问题了

**Comment by hanlinwu** [comment]
> 找到问题了

您好，我遇到了一样的问题，PSNR很低，请问您是否解决了？ 问题在哪里？

**Comment by boohit** [comment]
> > 找到问题了
> 
> 您好，我遇到了一样的问题，PSNR很低，请问您是否解决了？ 问题在哪里？
您好，请问您找到问题所在了吗？
